### ISSUE TITLE
Elaborate on CA public key

### ISSUE THREAD

**Issue by bwesterb** [davidben/merkle-tree-certs#27]
In `-00` we write

```
public_key: The public half of a signing keypair. The corresponding private key, private_key, is known only to the CA.
```

This needs elaboration. We could pick one post-quantum signature scheme, as we have picked SHA256 as hash. Say Dilithium2. It's not unconceivable that we'll want to migrate to a new signature scheme. Perhaps because Dilithium2's security is weaker than expected, but more likely because a significantly better post-quantum signature scheme has stabilised.

ProofType should afford enough flexibility for this.

Alternatively, we can simply use a `TLSSubjectInfo`-like structure for the CA public key.

A different idea, is to use a stateful hash based signature such as LMS or XMSS. There is no need to keep state: instead we can use the `n`th one-time-signature for the `n`th window. Clients can check whether the right OTS is used. Then if the CA accidentally signs and published the same window twice, then the private key is only compromised for that window, which will be ignored anyway by TSs if such a thing happens. With `n=16`, `h=20` and `w=16`, a key pair will last 119 years, signatures will be 880 bytes, verification will take 1,181 SHA2 hashes and keygen 1 billion SHA2 hashes. The upside is that this is definitely post-quantum secure. But this is all rather more complicated to implement than a plain signature, so I suppose we're better of sticking with Dilithium for now and accept we might have to change at some point. (This would complicate signing revocation lists.)

**Comment by davidben** [comment]
We probably don't need to optimize the signature here too much, compared to more fast-issuance schemes. We effectively amortize everything relating to the CA's key on the CA -> TS -> RP path. Keys and signatures barely even show up on the wire, though yeah we'll certainly need to define it as part of I guess #12.

The trick with using the counter in lieu of state is fun. I suppose, yeah, this is a place where stateful hash-based sigs are less of a disaster. But given the signature is not that load-bearing, I think "don't do anything interesting and pick something default" is the way to go. :-)

**Comment by davidben** [comment]
> Shouldn't they also be sent to the browser?

Yeah, at least usually. :-) But it also happens in the RP <-> TS flow which is left somewhat unspecified. I expect browsers, for instance, would reuse their update protocols. Right now the text says:

> The transparency service publishes the mirrored CA state using the same interface as {{publishing}}. The protocol between the relying party and transparency service is out of scope of this document. The relying party MAY use the interface defined here, or an existing application-specific authenticated channel.
>
> As discussed in {{authenticity}}, relying parties MUST ensure that any windows obtained were asserted by the CA. This SHOULD be done by having the transparency service forward the CA's signature, with the relying party verifying it. However, if the transparency service already maintains a trusted, authenticated channel to the relying parties (e.g. a software or root store update channel), relying parties MAY rely on the transparency service to validate the CA windows on their behalf, only sending valid windows over this channel.

Either way, yeah, we do need to define the structure with the signed window structure because the CA <-> TS flow needs to be defined. (We actually don't _need_ define the public key format because that's never transmitted anywhere. It's part of your application-local root store configuration story. But defining a format for convenience makes sense anyway.)
