### ISSUE TITLE
Clarify that unparsable signing inputs are still misissuance

### ISSUE THREAD

**Issue by davidben** [davidben/merkle-tree-certs#5]
We currently say:

> If the CA's private key signs an input that can be interpreted as a LabeledWindow structure, the CA is considered to have certified every assertion contained in every value in the `tree_heads` list, with expiry determined by `batch_number`, the position of the tree head in the list, and the CA's input parameters as described in {{parameters}}.

But this leaves open what if the CA's private key signs an input that can't be parsed. Buggy parsers in the RP are bad, but they shouldn't be instant security bugs. To fix that, we should say:

* If the CA's private key signs *any* input beginning with `Merkle Tree Certificate Window\0`, it is in scope for this document. If it cannot be parsed as a LabeledWindow, or if the hashes were invalid, this is misissuance.
* Signing other labels is, a priori, also misissuance, though future protocol extensions MAY define other label prefixes that do have meaning. I.e., if we want to have the CA sign other messages with the same key, we may define a different label for it, but the CA shouldn't be allowed to just randomly sign stuff that seems like fun.

**Comment by davidben** [comment]
It's implied, but we should probably also spell it out explicitly: it doesn't matter if the CA ever served the signature over the HTTP interface. If it generated such a signature, it issued it and is responsible for whatever it signed.

**Comment by bwesterb** [comment]
There is another case: if a signature is served, which itself does not verify, then we should not count it as a misissuance. The signature would not be trusted anyway (as it doesn't verify), and this gives some robustness against some bitflips. #26

**Comment by davidben** [comment]
Oh yeah, there's "I cannot parse the signature" and "you signed a thing that does not parse but has the right context string". I meant the latter. I'll go rename the issue to be clearer.

Agreed that if the signature doesn't verify, it's not misissuance. The system has misbehaved, but I think that can be thought of as a generalized outage. Specifically, it doesn't cause a durable security problem the way having a bad signature in the world does.
